# Generated by Django 3.2 on 2022-06-19 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0004_mycollection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycollection',
            name='user',
        ),
        migrations.AlterField(
            model_name='mycollection',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='id'),
        ),
    ]
