# Generated by Django 3.2 on 2022-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20220620_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycollection',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
