# Generated by Django 3.2 on 2022-06-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_mycollection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycollection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
