# Generated by Django 3.2 on 2022-06-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_mycollection_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
