# Generated by Django 4.0.5 on 2022-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_mycollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycollection',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
